import {
    defaults as T08, SETTINGS_CASE_FIXED_TIME,
    SETTINGS_CASE_VARIABLE_TIME,
    SETTINGS_INFILTRATION_CONTINUOUS,
    SETTINGS_INFILTRATION_ONE_TIME
} from './defaults';

export {
    T08,
    SETTINGS_CASE_FIXED_TIME,
    SETTINGS_CASE_VARIABLE_TIME,
    SETTINGS_INFILTRATION_CONTINUOUS,
    SETTINGS_INFILTRATION_ONE_TIME
};
